name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-workflow.yml'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-workflow.yml'

jobs:
  test-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build frontend
        run: npm run build

      - name: Start Vite preview server
        run: |
          npm run preview -- --port 3000 &
          echo "SERVER_PID=$!" >> $GITHUB_ENV
        env:
          NODE_ENV: production

      - name: Wait for preview server to be ready
        run: |
          n=0
          until curl -s http://localhost:3000 || [ $n -ge 10 ]; do
            echo "Waiting for preview server..."
            sleep 2
            n=$((n+1))
          done

      - name: Run Playwright tests
        run: npm run test:ui

      - name: Stop preview server
        run: kill $SERVER_PID
